### PR TITLE
Feature mission profile

### PR DESCRIPTION
**Pull request by vikipretium**
## Issues fixed
- Render a list of all joined missions (use filter()) on the "My profile" page. ✔️ 
Outer Space Thumbs Up GIF by NASA
Thanks for reviewing my pull request 👍🏼

### CODE REVIEW

**Comment by ZahraArshia** [comment]
Hello dear @vikipretium,
well, I'm afraid it's not working for me, maybe I'm mistaken, or you push something else by mistake, I wanted to record a loom to  show the issue, but apparently the loom servers are down! 🤷‍♀️
when I add missions, they don't display in the profile page.
Also, I think something happened to the `NavBar `styles:
image
look at the separation line between `Dragons `and `MyProfile`.
Also, the border around reserved sections is gone, is it intentional?
image

**Comment by vikipretium** [comment]
I am extremely sorry @ZahraArshia. I made everything work and I forgot to push the changes and create this pull request. 🙏🏼

**Comment by ZahraArshia** [comment]
Yeah I guessed that might be the case 😁
It's fine dear

**Review by iLynette — APPROVED** [review]
Hello @vikipretium 👋🏾 

Good job implementing the changes. Your project is complete. Go ahead and merge it.
Congratulations-Memes-FEATURED

**Pull request merged**
